### PR TITLE
Modify setting image format before setting resolution

### PR DESCRIPTION
**Pull request by SLBiuBiu**
Modify the image format setting before setting the resolution. If it is set after the resolution, it will not work.

### CODE REVIEW

**Comment by neozhaoliang** [comment]
Thank you!

**Comment by JaiKumar-Singh** [comment]
Hi @SLBiuBiu, It seems you had successfully run the code. Can you please share the Fisheye dataset used in this code or even the output video of "car.mp4"(with original resolution 1200x1600)? 
Any help will be much appreciated!

**Comment by SLBiuBiu** [comment]
> Hi @SLBiuBiu, It seems you had successfully run the code. Can you please share the Fisheye dataset used in this code or even the output video of "car.mp4"(with original resolution 1200x1600)? Any help will be much appreciated!

@JaiKumar-Singh  Sorry, my fisheye dataset is of no help to you, you need to calibrate your fisheye camera.

**Comment by neozhaoliang** [comment]
@JaiKumar-Singh I guess you want a full-size surround view video, together with the camera parameters, to compute the actual coordinates of the parking lines and obstacles?  If this, my original video is 1600x1200 and down-sampled to 640x480, the aspect ratio is still 4:3, so you can try resize it back? But if you want the four individual camera videos, then I cannot help here,

**Pull request merged**
